MCU = STM32F303
DFU_ARGS = -d 0483:df11 -a 0 -s 0x08000000:leave

RGBLIGHT_ENABLE = yes
BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes

# CONSOLE_ENABLE = yes
COMMAND_ENABLE = yes
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
TAP_DANCE_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
# WPM_ENABLE = yes

RGB_MATRIX_ENABLE = IS31FL3741